apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Change-log-level

permissions:
  id-token: write
  scm-token-own: read
  scm-token-org: read

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - preprod
          - qa
          - prod
        default: preprod
        description: 'Select the environment'
      loglevel:
        type: choice
        options: [DEBUG, INFO, WARN]
        default: WARN
        description: 'Select the desired log level'
      service:
        type: choice
        options:
          - admin-tools [not supported]
          - analytics-service [not supported]
          - api-gateway
          - asset-service
          - audit-service
          - auth-service
          - cb-action-helper
          - ci-insights-service
          - client-data
          - data-ingestion-service [not supported]
          - db-service [not supported]
          - endpoint-service
          - entitlement-service
          - event-processing-service
          - extension-service
          - external-ci-service
          - external-workflow-service
          - flag-service
          - fm-impressions-service
          - instrumentation-service
          - keycloak [not supported]
          - log-service
          - nextgen-ui [not supported]
          - ng-tekton-dispatch-service
          - notification-service
          - open-telemetry-exporter
          - otel-collector-jenkins
          - projectmgmt-service
          - property-service
          - rbac-service
          - reports-service
          - repository-service
          - run-service
          - scm-service [not supported]
          - sdk-notification-service
          - search-service [not supported]
          - secret-service
          - telegraf-input-impressions [not supported]
          - tekton-config [not supported]
          - ticketing-service
        required: true
        description: 'Select the service'
      advanced:
        type: string
        required: false
        description: |
          Optional field to target a specific packages/log levels.
          Additional details available here:
          https://cloudbees.atlassian.net/wiki/spaces/SDP/pages/3835756607/How+to+change+a+CBP+service+s+log+level+at+runtime\n\n
          note: loglevel will be overwritten by the configuration file
      justification:
        type: string
        required: true
        description: 'Why does the log level need to be updated? E.g.: Jira Ticket #, bug being investigated, etc... '

jobs:
  change-log-level:
    env:
      ENVIRONMENT: ${{ inputs.env }}
      LOGLEVEL: ${{ inputs.loglevel }}
      SERVICE: ${{ inputs.service }}
      JUSTIFICATION: ${{ inputs.justification }}
      PACKAGE: ${{ inputs.advanced }}
    environment: ${{ inputs.env }}
    steps:
      - name: Login to AWS Account
        uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.assume_role_arn_log_manager }}
          role-duration-seconds: "900"

      - name: Set cluster name and copy secrets file
        uses: docker://amazon/aws-cli
        id: setcluster
        run: |
          echo "eks-${ENVIRONMENT}-us-east-1" | tr -d '\n' > $CLOUDBEES_OUTPUTS/cluster_name_east
          echo "eks-${ENVIRONMENT}-us-west-2" | tr -d '\n' > $CLOUDBEES_OUTPUTS/cluster_name_west
          echo "_________ GET SECRETS FILE ________"
          aws secretsmanager get-secret-value --secret-id ${ENVIRONMENT}-platform-secrets.yaml --query SecretString --output text --region us-east-1 > secrets.yaml

      - name: "Configure EKS credentials - East"
        id: eks_us_east_1
        uses: cloudbees-io/configure-eks-credentials@v1
        with:
          name: ${{ steps.setcluster.outputs.cluster_name_east }}
          region: us-east-1
          alias: platform-east

      - name: "Configure EKS credentials - West"
        id: eks_us_west_2
        uses: cloudbees-io/configure-eks-credentials@v1
        with:
          name: ${{ steps.setcluster.outputs.cluster_name_west }}
          region: us-west-2
          alias: platform-west

      - name: Change log level
        id: change_log_level
        uses: docker://ghcr.io/helmfile/helmfile:v1.1.3
        env:
          SERVICE: ${{ inputs.service }}
          LEVEL: ${{ inputs.loglevel }}
        run: |
          contexts=(
            "platform-east"
            "platform-west"
          )
          echo "========================================================"
          echo "========================================================";echo
          if [[ -z "$PACKAGE" ]]; then
              echo "Setting $SERVICE log level to $LOGLEVEL.";echo
          else
              echo "Setting $SERVICE log levels as described in:"
              echo $PACKAGE;echo
          fi
          echo "========================================================"
          echo "========================================================";echo

          for context in "${contexts[@]}"; do
            echo "--- Switching to context: $context ---"
            kubectl config use-context "$context" > /dev/null 2>&1

            echo "Looking for pods with service name: $SERVICE"
            pods=$(kubectl get pods -n platform --no-headers -o custom-columns=":metadata.name" | grep "$SERVICE")

            if [ -z "$pods" ]; then
                echo "No pods found for $SERVICE in $context."
                continue
            fi

            for pod in $pods; do
                # Fetching the port from the pod
                TARGET_PORT=$(kubectl get pod "$pod" -n platform -o jsonpath='{.spec.containers[*].env[?(@.name=="SERVER_LISTEN_PORT")].value}')

                # Bail if the port isn't found
                if [ -z "$TARGET_PORT" ]; then
                    echo "Could not find SERVER_LISTEN_PORT for $pod...aborting"
                    exit 1
                fi 

                echo "Processing $pod using port $TARGET_PORT..."
                
                kubectl port-forward pod/"$pod" $TARGET_PORT:$TARGET_PORT --namespace platform > /dev/null 2>&1 &
                pf_pid=$!

                # Allow some time for port-forwarding to set up
                sleep 4

                # Execute curl to set log level
                response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "https://localhost:$TARGET_PORT/z/loglevel?level=$LOGLEVEL" --insecure)
                # Check if advanced mode was used
                if [[ -z "$PACKAGE" ]]; then
                    # Execute curl to set log level for the service
                    response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "https://localhost:$TARGET_PORT/z/loglevel?level=$LOGLEVEL" --insecure)
                    if [[ "$response" -eq 200 ]]; then
                        echo "[$pod] Successfully set log level to $LOGLEVEL"
                    else
                        echo "[$pod] Error setting log level. Response code: $response"
                    fi
                else
                    # Save the log level adjustments to a JSON file
                    echo "$PACKAGE" > log_config.json
    
                    # Execute curl with POST using the JSON file
                    response=$(curl -s -o /dev/null -w "%{http_code}" -XPOST --max-time 5 "https://localhost:$TARGET_PORT/z/loglevels" --insecure -d @log_config.json)
                    if [[ "$response" -eq 200 ]]; then
                        echo "[$pod] Successfully applied custom log level settings"
                    else
                        echo "[$pod] Error setting log level. Response code: $response"
                    fi
                fi

                echo

                # Kill the port-forward process
                kill "$pf_pid"
            done
          done

      - name: Publish evidence
        uses: https://github.com/cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            - Changing log level of ${{ inputs.service }}
            - to: ${{ inputs.advanced != '' && inputs.advanced || inputs.loglevel }}
            - with the justification: ${{ inputs.justification }}